apiVersion: v1
kind: Service
metadata:
  name: app-store-front-service
  namespace: app-store-api
spec:
  type: NodePort
  selector:
    app: app-store-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081